language: python
dist: xenial

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

branches:
  only:
  - master

matrix:
  allow_failures:
  - python: "nightly"

before_install:
  - pip install pycodestyle mypy==0.670 # See https://github.com/python/mypy/issues/6564
  - pycodestyle . --count
  - mypy --ignore-missing-imports --check-untyped-defs telluric/

install:
  - pip install numpy  # Required
  - pip install --prefer-binary .  # Test installation correctness
  - pip install .[dev]  # Test development dependencies

script:
  - pytest -vv  # Test against installed code

after_success:
  # Uninstall to test coverage against sources
  - pip uninstall telluric -y
  - pip install --editable .

  - pytest --cov

  # Publish coverage
  - pip install codecov
  - codecov
